version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - FIREBASE_CONFIG=${FIREBASE_CONFIG}
    networks:
      - webforge-network

networks:
  webforge-network:
    driver: bridge